version: '3.9'

services:
  mariadb:
    build:
      context: .
      dockerfile: Dockerfile_mariadb
    container_name: mariadb_container
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: school_db
      MYSQL_USER: flask_user
      MYSQL_PASSWORD: flask_password

  flask_app:
    build:
      context: .
      dockerfile: Dockerfile_flask
    container_name: flask_app_container
    ports:
      - "5000:5000"
    depends_on:
      - mariadb
    environment:
      FLASK_APP: app
      FLASK_ENV: development
      FLASK_DB_HOST: mariadb
      FLASK_DB_USER: flask_user
      FLASK_DB_PASSWORD: flask_password
      FLASK_DB_NAME: school_db

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus_container
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

  grafana:
    image: grafana/grafana:latest
    container_name: grafana_container
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana

  mysqld_exporter:
    image: prom/mysqld-exporter:latest
    container_name: mysqld_exporter_container
    environment:
      - DATA_SOURCE_NAME=flask_user:flask_password@tcp(mariadb:3306)/school_db
    depends_on:
      - mariadb
    ports:
      - "9104:9104"

volumes:
  db_data:
  grafana_data:
