global:
  scrape_interval: 15s  # Intervalo padrão de coleta de métricas

scrape_configs:
  # Configuração para coletar métricas da aplicação Flask
  - job_name: 'flask_app'
    static_configs:
      - targets: ['flask_app_container:5000']  # Nome do serviço e porta configurados no Docker Compose

  # Configuração para coletar métricas do MariaDB através do mysqld_exporter
  - job_name: 'mysqld_exporter'
    static_configs:
      - targets: ['mysqld_exporter_container:9104']  # Nome do serviço e porta configurados no Docker Compose
